const queryAllRisk = [
  {
      "addvcd": "500101139000",
      "latitude": 30.66889,
      "townId": null,
      "emeType_dictText": "巡险",
      "stcd": "60512565",
      "patrolZ": null,
      "name": "甘宁水库",
      "emeType": "1",
      "waterLevel": null,
      "time": null,
      "stType": null,
      "avoidZ": null,
      "longitude": 108.28235
  },
  {
      "addvcd": "500101151000",
      "latitude": 30.60773,
      "townId": null,
      "emeType_dictText": "巡险",
      "stcd": "2",
      "patrolZ": null,
      "name": "登丰水库",
      "emeType": "1",
      "waterLevel": null,
      "time": null,
      "stType": null,
      "avoidZ": null,
      "longitude": 108.63875
  },
  {
      "addvcd": "500101151000",
      "latitude": 30.60844002,
      "townId": "27",
      "emeType_dictText": "避险",
      "stcd": "2",
      "patrolZ": null,
      "stType_dictText": "重点场镇",
      "name": "龙驹           ",
      "emeType": "3",
      "waterLevel": null,
      "time": null,
      "stType": "5",
      "avoidZ": null,
      "longitude": 108.6358035
  },
  {
      "addvcd": "500101024000",
      "latitude": 30.759731,
      "townId": null,
      "emeType_dictText": "巡险",
      "stcd": "1",
      "patrolZ": null,
      "name": "甘宁水库",
      "emeType": "1",
      "waterLevel": null,
      "time": null,
      "stType": null,
      "avoidZ": null,
      "longitude": 108.449898
  }
]
const queryAllSites = [
    {
        "addvcd": "500101135000",
        "latitude": 30.64289842,
        "townId": "1",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "瘦畔河龙沙场镇 ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.229359
    },
    {
        "addvcd": "500101152000",
        "latitude": 30.5687316,
        "townId": "2",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "走马场         ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.4418811
    },
    {
        "addvcd": "500101144000",
        "latitude": 30.72018606,
        "townId": "3",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "分水场         ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.0854232
    },
    {
        "addvcd": "500101132000",
        "latitude": 30.72987182,
        "townId": "4",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "孙家场         ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.0150222
    },
    {
        "addvcd": "500101158203",
        "latitude": 30.59623745,
        "townId": "5",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "瑞池场         ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.1520234
    },
    {
        "addvcd": "500101141000",
        "latitude": 30.9012505,
        "townId": "6",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "熊家场         ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.4330091
    },
    {
        "addvcd": "500101234200",
        "latitude": 30.66434447,
        "townId": "7",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "龙头村         ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.793046
    },
    {
        "addvcd": "500101151004",
        "latitude": 30.65816933,
        "townId": "8",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "赶场场         ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.6061752
    },
    {
        "addvcd": "500101147000",
        "latitude": 30.84948311,
        "townId": "9",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "弹子镇         ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.0002947
    },
    {
        "addvcd": "500101148000",
        "latitude": 30.77788393,
        "townId": "10",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "长岭镇         ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.4714834
    },
    {
        "addvcd": "500101237000",
        "latitude": 30.57264448,
        "townId": "11",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "普子           ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.8177639
    },
    {
        "addvcd": "500101238000",
        "latitude": 30.65908847,
        "townId": "12",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "地宝乡         ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.8967181
    },
    {
        "addvcd": "500101143201",
        "latitude": 30.79428117,
        "townId": "13",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "李河镇高升场   ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.1956348
    },
    {
        "addvcd": "500101143000",
        "latitude": 30.81629124,
        "townId": "14",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "李河           ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.268495
    },
    {
        "addvcd": "500101142000",
        "latitude": 30.82182249,
        "townId": "15",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "高梁镇         ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.30152
    },
    {
        "addvcd": "500101152002",
        "latitude": 30.58354106,
        "townId": "16",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "小河社区       ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.5113674
    },
    {
        "addvcd": "500101155000",
        "latitude": 30.68505045,
        "townId": "17",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "新长滩坝上     ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.6110457
    },
    {
        "addvcd": "500101155003",
        "latitude": 30.76410281,
        "townId": "18",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "向家社区       ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.7188159
    },
    {
        "addvcd": "500101019000",
        "latitude": 30.7604234,
        "townId": "19",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "双河口街道     ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.365366
    },
    {
        "addvcd": "500101137004",
        "latitude": 30.57281236,
        "townId": "20",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "石桥社区       ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.232124
    },
    {
        "addvcd": "500101149002",
        "latitude": 30.77347582,
        "townId": "21",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "五一社区       ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.0128639
    },
    {
        "addvcd": "500101152003",
        "latitude": 30.6040426,
        "townId": "22",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "双流           ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.4759296
    },
    {
        "addvcd": "500101157000",
        "latitude": 30.5964133,
        "townId": "23",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "白土           ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.8091657
    },
    {
        "addvcd": "500101158000",
        "latitude": 30.56167688,
        "townId": "24",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "郭村           ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.166461
    },
    {
        "addvcd": "500101145000",
        "latitude": 30.80916269,
        "townId": "25",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "余家           ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 107.9572666
    },
    {
        "addvcd": "500101155000",
        "latitude": 30.73937276,
        "townId": "26",
        "stcd": null,
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "长滩           ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.6009477
    },
    {
        "addvcd": "500101151000",
        "latitude": 30.60844002,
        "townId": "27",
        "stcd": "2",
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "龙驹           ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.6358035
    },
    {
        "addvcd": "500101139000",
        "latitude": 30.6813825,
        "townId": "28",
        "stcd": "60512565",
        "patrolZ": null,
        "stType_dictText": "重点场镇",
        "name": "甘宁乡         ",
        "emeType": null,
        "waterLevel": null,
        "time": null,
        "stType": "5",
        "avoidZ": null,
        "longitude": 108.242381
    },
    {
        "addvcd": "500101139000",
        "latitude": 30.714022,
        "townId": null,
        "stcd": "60512565",
        "patrolZ": 15,
        "stType_dictText": "水位站",
        "name": "甘宁水库",
        "emeType": null,
        "waterLevel": 18,
        "time": "2023-11-22 07:00",
        "stType": "3",
        "avoidZ": null,
        "longitude": 108.225769
    },
    {
        "addvcd": "500101151000",
        "latitude": 29.642,
        "townId": null,
        "stcd": "2",
        "patrolZ": 637.5,
        "stType_dictText": "水库",
        "name": "登丰水库",
        "emeType": null,
        "waterLevel": 641,
        "time": "2023-11-22 07:00",
        "stType": "1",
        "avoidZ": 639.8,
        "longitude": 104.63
    },
    {
        "addvcd": "500101150000",
        "latitude": 30.777642,
        "townId": null,
        "stcd": "0286cb9a3eb440c7aaf65e6e6173d3b4",
        "patrolZ": null,
        "stType_dictText": "视频监控站",
        "name": "香溪河深渡桥视频站",
        "emeType": null,
        "waterLevel": 15.6,
        "time": "2023-11-22 07:00",
        "stType": "4",
        "avoidZ": 15,
        "longitude": 108.287989
    },
    {
        "addvcd": "500101024000",
        "latitude": 30.519166,
        "townId": null,
        "stcd": "1",
        "patrolZ": 415,
        "stType_dictText": "水库",
        "name": "甘宁水库",
        "emeType": null,
        "waterLevel": 416,
        "time": "2023-11-22 07:00",
        "stType": "1",
        "avoidZ": 417,
        "longitude": 106.541
    }
]

export {
  queryAllRisk,
  queryAllSites
}
